### ISSUE TITLE
Problem when version_files contains many occurrences

### ISSUE THREAD

**Issue by jaimeph** [freepik-company/gommitizen#28]
Error when changing the version of my files when there are more than one `version`:

```
{
  "version": "1.21.0",
  "commit": "d20f354e9ce1e038db29cb1f5f1d459a7eeecb7d",
  "version_files": [
    "Chart.yaml:version"
  ],
  "prefix": "fc-istio"
}
``` 

```
apiVersion: v2
name: fc-istio
description: A Helm chart to deploy Istio on Kubernetes
type: application
version: 1.21.0
dependencies:
  # Releases: https://istio.io/latest/news/releases/

  # Ref: https://github.com/istio/istio/blob/master/manifests/charts/base
  - name: base
    alias: istio-base
    version: 1.21.0
    repository: https://istio-release.storage.googleapis.com/charts

  # Ref: https://github.com/istio/istio/blob/master/manifests/charts/base
  - name: istiod
    version: 1.21.0
    repository: https://istio-release.storage.googleapis.com/charts
```
